import { Inter } from "next/font/google";
import "./globals.css";
import "./Custom.css";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mezbah Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " dark-theme"}>
        <NextTopLoader
          color="var(--first-color)"
          height={2}
          speed={200}
          showSpinner={false}
        />
        {children}
      </body>
    </html>
  );
}
